name: Track GitHub Traffic

on:
  schedule:
    - cron: "0 0 * * *"  # Uruchamia skrypt codziennie o północy (UTC)
  workflow_dispatch:  # Pozwala uruchomić ręcznie

jobs:
  track-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Pobranie statystyk ruchu
        uses: jgehrcke/github-repo-stats@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Zapisanie danych do pliku
        run: |
          mkdir -p traffic_data
          mv repo-traffic.json traffic_data/traffic_$(date +%Y-%m-%d).json

      - name: Commit i push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add traffic_data/
          git commit -m "Aktualizacja danych o ruchu $(date +%Y-%m-%d)" || echo "Brak zmian"
          git push
